(*! © 2023 imaoki | MIT License | https://github.com/imaoki *)
         file = curves ;

       curves = { curve , "\n" }+ ;

        curve = degree
              , "," , spans
              , "," , form
              , "," , is_rational
              , "," , dimention
              , "/" , knot_values
              , "/" , cv_values ;

       degree = ? 1-7 ? ;

        spans = integer ;

         form = form_open | form_closed | form_periodic ;

  is_rational = boolean ;

    dimention = "2" | "3" ;

  knot_values = knot_value { "," , knot_value } ;

   knot_value = number ;

    cv_values = cv_value , { ";" , cv_value }+ ;

     cv_value = number , "," , number , "," number ;

    form_open = "0" ;

  form_closed = "1" ;

form_periodic = "2" ;

      boolean = "0" | "1" ;

       number = [ "-" ] , ( integer | real ) ;
